// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Unregistereduser struct {
	ID             int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	WhatsappNumber string
	DisplayName    string
}
